SYSTEM_FIELDS_REGISTRY = [
    {
        "key": "id",
        "name": "ID",
        "field_type": "number",
        "group_name": "系统",
        "options": None,
        "width": 60,
        "sortable": True,
        "filterable": False,
        "editable": False,
        "frozen": True,
        "visible": False,
    },
    {
        "key": "application_number",
        "name": "申请号",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 150,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "frozen": True,
        "visible": True,
    },
    {
        "key": "publication_number",
        "name": "公开号",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 140,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "title",
        "name": "标题",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 320,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "frozen": True,
        "visible": True,
    },
    {
        "key": "grant_number",
        "name": "授权号",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 140,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "applicant",
        "name": "申请人",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 160,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "inventor",
        "name": "发明人",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 140,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "assignee",
        "name": "专利权人",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 140,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "agent",
        "name": "代理机构",
        "field_type": "text",
        "group_name": "著录项目",
        "options": None,
        "width": 140,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "country",
        "name": "国家",
        "field_type": "select",
        "group_name": "著录项目",
        "options": ["CN", "US", "EP", "JP", "KR", "WO", "DE", "GB", "FR", "Other"],
        "width": 70,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "patent_type",
        "name": "专利类型",
        "field_type": "select",
        "group_name": "著录项目",
        "options": ["invention", "utility_model", "design", "pct"],
        "option_labels": {"invention": "发明", "utility_model": "实用新型", "design": "外观设计", "pct": "PCT"},
        "width": 90,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "filing_date",
        "name": "申请日",
        "field_type": "date",
        "group_name": "日期",
        "options": None,
        "width": 110,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "publication_date",
        "name": "公开日",
        "field_type": "date",
        "group_name": "日期",
        "options": None,
        "width": 110,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "grant_date",
        "name": "授权日",
        "field_type": "date",
        "group_name": "日期",
        "options": None,
        "width": 110,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "legal_status",
        "name": "法律状态",
        "field_type": "select",
        "group_name": "法律",
        "options": ["pending", "published", "examining", "granted", "rejected", "withdrawn", "deemed_withdrawn", "expired", "abandoned", "unknown"],
        "option_labels": {
            "pending": "待审", "published": "公开", "examining": "实审中", "granted": "授权",
            "rejected": "驳回", "withdrawn": "撤回", "deemed_withdrawn": "视撤",
            "expired": "终止", "abandoned": "放弃", "unknown": "未知",
        },
        "width": 90,
        "sortable": True,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "ipc_main",
        "name": "主IPC",
        "field_type": "text",
        "group_name": "分类",
        "options": None,
        "width": 110,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "category",
        "name": "技术分类",
        "field_type": "text",
        "group_name": "业务",
        "options": None,
        "width": 120,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "subcategory",
        "name": "子分类",
        "field_type": "text",
        "group_name": "业务",
        "options": None,
        "width": 120,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "module",
        "name": "功能模块",
        "field_type": "text",
        "group_name": "业务",
        "options": None,
        "width": 120,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "has_risk",
        "name": "有风险",
        "field_type": "boolean",
        "group_name": "风险",
        "options": None,
        "width": 70,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "risk_level",
        "name": "风险等级",
        "field_type": "select",
        "group_name": "风险",
        "options": ["none", "low", "medium", "high", "critical"],
        "option_labels": {"none": "无", "low": "低", "medium": "中", "high": "高", "critical": "极高"},
        "width": 80,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": True,
    },
    {
        "key": "technical_problem",
        "name": "技术问题",
        "field_type": "textarea",
        "group_name": "技术信息",
        "options": None,
        "width": 200,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "technical_solution",
        "name": "技术方案",
        "field_type": "textarea",
        "group_name": "技术信息",
        "options": None,
        "width": 240,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "technical_effect",
        "name": "技术效果",
        "field_type": "textarea",
        "group_name": "技术信息",
        "options": None,
        "width": 200,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "application_status",
        "name": "应用状态",
        "field_type": "select",
        "group_name": "业务",
        "options": ["not_applied", "evaluating", "applied", "monitoring", "abandoned"],
        "option_labels": {"not_applied": "未应用", "evaluating": "评估中", "applied": "已应用", "monitoring": "监控中", "abandoned": "已放弃"},
        "width": 90,
        "sortable": False,
        "filterable": True,
        "editable": True,
        "visible": False,
    },
    {
        "key": "notes",
        "name": "备注",
        "field_type": "textarea",
        "group_name": "其他",
        "options": None,
        "width": 160,
        "sortable": False,
        "filterable": False,
        "editable": True,
        "visible": False,
    },
    {
        "key": "created_at",
        "name": "录入时间",
        "field_type": "datetime",
        "group_name": "系统",
        "options": None,
        "width": 150,
        "sortable": True,
        "filterable": False,
        "editable": False,
        "visible": False,
    },
]

SYSTEM_FIELD_KEYS = {f["key"] for f in SYSTEM_FIELDS_REGISTRY}


def get_system_field_meta(key: str) -> dict | None:
    for f in SYSTEM_FIELDS_REGISTRY:
        if f["key"] == key:
            return f
    return None


def get_all_fields_meta(db) -> list[dict]:
    from app.models import CustomField
    fields = []
    for sf in SYSTEM_FIELDS_REGISTRY:
        fields.append({**sf, "is_system": True})
    custom_fields = db.query(CustomField).filter(CustomField.is_active == True).order_by(CustomField.sort_order, CustomField.name).all()
    for cf in custom_fields:
        fields.append({
            "key": cf.key,
            "name": cf.name,
            "field_type": cf.field_type.value if hasattr(cf.field_type, 'value') else str(cf.field_type),
            "group_name": cf.group_name or "自定义",
            "options": cf.options,
            "option_labels": None,
            "width": 140,
            "sortable": cf.field_type.value in ("text", "number", "date", "select", "boolean") if hasattr(cf.field_type, 'value') else True,
            "filterable": True,
            "editable": True,
            "frozen": False,
            "visible": True,
            "is_system": False,
            "is_ai": (cf.ai_config is not None),
            "ai_config": cf.ai_config,
            "description": cf.description,
            "id": cf.id,
            "sort_order": cf.sort_order,
        })
    return fields
